### ISSUE TITLE
got an issue database.json 

### ISSUE THREAD

**Issue by mrBoomDev** [FastestMolasses/Vouch-Pro-Discord-Bot#2]
Traceback (most recent call last):
  File "main.py", line 352, in <module>
    main()
  File "main.py", line 348, in main
    DiscordBot().run(config.DISCORD_TOKEN)
  File "main.py", line 18, in __init__
    allData = data.loadJSON(data.DATABASE_FILENAME)
  File "C:\Users\Aarons\Desktop\Vouch-Pro-Discord-Bot-master\data.py", line 91, in loadJSON
    with open(getFileName(fileName), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'database.json'

can you contact me on discord Rated#7667 i got over 850+ members

**Comment by webbrain-one** [comment]
Hi! Thanks for the report. I’ve opened PR #8 to fix the missing `database.json` error so the bot no longer crashes at startup.
